# Generated by Django 4.2.7 on 2023-11-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_brand_remove_product_manufacturer_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
