# Generated by Django 4.2.7 on 2023-11-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_product_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_product',
        ),
    ]
