# Generated by Django 4.2.7 on 2023-11-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app1_product_detail',
        ),
    ]
