# Generated by Django 4.2.7 on 2023-11-19 17:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
