# Generated by Django 4.2.5 on 2023-12-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lastprice',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
