# Generated by Django 4.2.5 on 2023-12-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_order_lastprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_price',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
